import { chromium } from "@playwright/test";
const base = "http://localhost:3200";
const out = "/tmp/claude-0/-home-user-Remoovals/9aaf5bb5-a8d7-505a-9eb5-464ae059be3c/scratchpad/shots";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await browser.newContext({ viewport: { width: 420, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto(base + "/start");
await page.fill('input[name="organiserName"]', "Josh");
await page.fill('input[name="name"]', "Sunday Golf");
await page.check('input[name="sport"][value="golf"]');
await page.click('button:has-text("Create crew")');
await page.waitForURL(/welcome=1/);
await page.click('a:has-text("Pin a session")');
await page.check('input[name="sport"][value="golf"]');
await page.fill('input[name="title"]', "Saturday fourball");
await page.fill('input[name="venueName"]', "Richmond Park");
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/venue-search.png` });
await page.fill('input[name="capacity"]', "4");
await page.click('button:has-text("Pin it")');
await page.waitForURL(/pinned=1/);
await page.locator('details', { hasText: "Pick the course" }).scrollIntoViewIfNeeded();
await page.screenshot({ path: `${out}/course-picker.png`, fullPage: true });
await page.locator('input[aria-label="Course name"]').fill("Richmond Park, Prince's");
await page.locator('input[aria-label="Tee set"]').fill("White");
await page.locator('input[aria-label="Pars in hole order"]').fill("4 4 3 5 4 4 3 4 5 4 3 4 5 4 4 3 4 5");
await page.locator('input[aria-label="Stroke indexes in hole order"]').fill("7 3 15 1 11 9 17 5 13 8 16 2 10 4 12 18 6 14");
await page.locator('button:has-text("Preview card")').click();
await page.getByText("Typed card").waitFor();
await page.locator('button:has-text("Use this card")').scrollIntoViewIfNeeded();
await page.screenshot({ path: `${out}/course-draft.png`, fullPage: true });
await page.click('button:has-text("Use this card")');
await page.locator("p", { hasText: "Card:" }).waitFor();
await page.screenshot({ path: `${out}/course-set.png`, fullPage: true });
await browser.close();
