import { chromium } from "@playwright/test";
const base = "http://localhost:3200";
// Usage: SHOTS_DIR=./shots [PLAYWRIGHT_CHROMIUM_PATH=...] node scripts/dev/golf.mjs, against `next start -p 3200` on a fresh DB.
const out = process.env.SHOTS_DIR ?? "./shots";
const browser = await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_PATH ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_PATH } : {});
const ctx = await browser.newContext({ viewport: { width: 420, height: 900 }, deviceScaleFactor: 2 });
const page = await ctx.newPage();
await page.goto(base + "/start");
await page.fill('input[name="organiserName"]', "Josh");
await page.fill('input[name="name"]', "Sunday Golf");
await page.check('input[name="sport"][value="golf"]');
await page.click('button:has-text("Create crew")');
await page.waitForURL(/welcome=1/);
await page.click('a:has-text("Pin a session")');
await page.check('input[name="sport"][value="golf"]');
await page.fill('input[name="title"]', "Saturday fourball");
await page.fill('input[name="venueName"]', "Richmond Park");
await page.fill('input[name="capacity"]', "4");
await page.click('button:has-text("Pin it")');
await page.waitForURL(/pinned=1/);
await page.locator('input[aria-label="Course name"]').fill("Richmond Park, Prince's");
await page.locator('input[aria-label="Tee set"]').fill("White");
await page.locator('input[aria-label="Pars in hole order"]').fill("4 4 3 5 4 4 3 4 5 4 3 4 5 4 4 3 4 5");
await page.locator('input[aria-label="Stroke indexes in hole order"]').fill("7 3 15 1 11 9 17 5 13 8 16 2 10 4 12 18 6 14");
await page.locator('button:has-text("Preview card")').click();
await page.getByText("Typed card").waitFor();
await page.click('button:has-text("Use this card")');
await page.locator("p", { hasText: "Card:" }).waitFor();
const card = page.locator("details", { hasText: "Your card" });
await card.locator('input[aria-label="Playing handicap"]').fill("14");
const scores = [5, 4, 3, 6, 4, 5, 2, 4, 5, 4, 4, 5, 5, 4, 6, 3, 4, 5];
for (let i = 0; i < scores.length; i++) await card.locator(`input[aria-label="Hole ${i + 1} gross"]`).fill(String(scores[i]));
await card.locator("ol").scrollIntoViewIfNeeded();
await page.screenshot({ path: `${out}/scorer.png` });
await card.locator('button:has-text("Save card")').click();
await page.locator("table", { hasText: "Player" }).waitFor();
await page.locator("section", { hasText: "Stableford" }).last().scrollIntoViewIfNeeded();
await page.screenshot({ path: `${out}/scorer-saved.png` });
const og = await ctx.request.get(page.url().split("?")[0] + "/opengraph-image");
const fs = await import("node:fs");
fs.writeFileSync(`${out}/og-golf.png`, Buffer.from(await og.body()));
// A brand-new crew has no table rows yet, so look the organiser's id up in the local database.
const { createClient } = await import("@libsql/client");
const row = (await createClient({ url: "file:./data/shots.db" }).execute("select id from users order by created_at limit 1")).rows[0];
await page.goto(page.url().replace(/\/s\/.*$/, `/players/${row.id}`), { waitUntil: "networkidle" });
await page.locator("section", { hasText: "Stableford" }).first().scrollIntoViewIfNeeded();
await page.screenshot({ path: `${out}/player-golf.png` });
await browser.close();
