import { chromium } from "@playwright/test";
const out = "/tmp/claude-0/-home-user-Remoovals/9aaf5bb5-a8d7-505a-9eb5-464ae059be3c/scratchpad/shots";
const base = "http://localhost:3200";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await browser.newContext({ viewport: { width: 420, height: 900 }, deviceScaleFactor: 2 });
await ctx.addCookies([{ name: "rc_session", value: "demo-organiser-session-L4jB9x3t3PqVrV2hOT1Xcd4I", domain: "localhost", path: "/" }]);
const p = await ctx.newPage();
await p.goto(base + "/crew/tuesday-fc", { waitUntil: "networkidle" });
const href = await p.locator('a[href*="/s/"]').first().getAttribute("href");
await p.goto(base + "/crew/tuesday-fc/season", { waitUntil: "networkidle" });
await p.screenshot({ path: out + "/season.png", fullPage: true });
const anon = await browser.newContext({ viewport: { width: 420, height: 900 }, deviceScaleFactor: 2 });
const s = await anon.newPage();
await s.goto(base + href, { waitUntil: "networkidle" });
await s.screenshot({ path: out + "/preview.png", fullPage: true });
const r = await anon.request.get(base + "/crew/tuesday-fc/season/opengraph-image");
const fs = await import("node:fs"); fs.writeFileSync(out + "/og-season.png", await r.body());
const d = await browser.newContext({ viewport: { width: 1280, height: 900 } });
await d.addCookies([{ name: "rc_session", value: "demo-organiser-session-L4jB9x3t3PqVrV2hOT1Xcd4I", domain: "localhost", path: "/" }]);
const f = await d.newPage();
await f.goto(base + "/founder", { waitUntil: "networkidle" });
await f.screenshot({ path: out + "/founder.png", fullPage: true });
await browser.close();
console.log("ok");
